# Generated by Django 4.2 on 2024-10-22 18:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('purchase_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_sales', to='usuarios.user')),
                ('seller_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='seller_sales', to='usuarios.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('product_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='produtos.product')),
                ('sale_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='loja.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
