# Generated by Django 4.2 on 2025-04-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='produtos.product'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='loja.sale'),
        ),
    ]
