# Generated by Django 4.2 on 2025-08-06 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('habits', models.TextField(blank=True, null=True)),
                ('nutrition', models.TextField(blank=True, null=True)),
                ('recommended_environment', models.TextField(blank=True, null=True)),
                ('average_lifespan_years', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('photo_path', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('breed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pet.breed')),
                ('pet_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_owned', to='usuarios.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='specie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='pet.specie'),
        ),
    ]
