# Generated by Django 4.2 on 2024-11-29 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_userdocument_unique_together'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='species_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='pet.specie'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pet.breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_owned', to='usuarios.user'),
        ),
    ]
