# Generated by Django 4.2 on 2024-11-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_breed_species_id_alter_pet_breed_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='species_id',
            new_name='specie_id',
        ),
    ]
