# Generated by Django 4.2 on 2024-10-22 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s\\d{5}-\\d{4}$', message='Número de telefone inválido')])),
                ('role', models.CharField(choices=[('médico veterinário', 'Medico Vet'), ('groomer', 'Groomer'), ('atendente', 'Atendente'), ('assistente veterinario', 'Assis Vet'), ('estagiario', 'Estagiario'), ('caixa', 'Caixa'), ('zelador', 'Zelador'), ('entregador', 'Entregador'), ('outro', 'Outro')], max_length=50)),
                ('area', models.CharField(choices=[('saude', 'Saude'), ('hotel', 'Hotel'), ('banho/tosa', 'Banhotosa'), ('loja', 'Loja')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('photo_path', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='usuarios.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('doc_type', models.CharField(choices=[('cnpj', 'Cnpj'), ('cpf', 'Cpf'), ('rg', 'Rg'), ('crmv', 'Crmv')], max_length=50)),
                ('doc_number', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='usuarios.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAudio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('audio_path', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='usuarios.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
