# Generated by Django 4.2 on 2025-08-06 21:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s\\d{5}-\\d{4}$', message='Número de telefone inválido')])),
                ('role', models.CharField(choices=[('medico_veterinario', 'Medico Vet'), ('groomer', 'Groomer'), ('atendente_saude', 'Atendente Saude'), ('atendente_hotel', 'Atendente Hotel'), ('atendente_loja', 'Atendente Loja'), ('atendente_banhotosa', 'Atendente Banhotosa'), ('assistente_veterinario', 'Assist Vet'), ('estagiario', 'Estagiario'), ('caixa', 'Caixa'), ('zelador', 'Zelador'), ('entregador', 'Entregador'), ('superuser', 'Superuser'), ('user', 'User'), ('outro', 'Outro')], max_length=50)),
                ('area', models.CharField(choices=[('saude', 'Saude'), ('hotel', 'Hotel'), ('banho/tosa', 'Banhotosa'), ('loja', 'Loja'), ('user', 'User'), ('geral', 'Geral'), ('superuser', 'Superuser')], max_length=50)),
                ('auth_service_id', models.UUIDField(editable=False, unique=True)),
                ('username', models.CharField(editable=False, max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^(?!.*[_-]{2})(?![-_])(?=.{1,25}$)[A-Za-z0-9._-]+(?<![-_])$', message='Username inválido. Deve ter no máximo 25 caracteres, pode conter letras, números, ponto, sublinhado ou hífen, não pode começar ou terminar com um caractere especial, e não pode ter caracteres especiais consecutivos.')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('photo_path', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='usuarios.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAudio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('audio_path', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='usuarios.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('doc_type', models.CharField(choices=[('cnpj', 'Cnpj'), ('cpf', 'Cpf'), ('rg', 'Rg'), ('crmv', 'Crmv')], max_length=50)),
                ('doc_number', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='usuarios.user')),
            ],
            options={
                'unique_together': {('doc_type', 'doc_number')},
            },
        ),
    ]
