# Generated by Django 4.2 on 2024-10-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('médico veterinário', 'Medico Vet'), ('groomer', 'Groomer'), ('atendente', 'Atendente'), ('assistente veterinario', 'Assis Vet'), ('estagiario', 'Estagiario'), ('caixa', 'Caixa'), ('zelador', 'Zelador'), ('entregador', 'Entregador'), ('superuser', 'Superuser'), ('outro', 'Outro')], max_length=50),
        ),
    ]
