# Generated by Django 4.2 on 2024-10-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('saude', 'Saude'), ('hotel', 'Hotel'), ('banho/tosa', 'Banhotosa'), ('loja', 'Loja'), ('user', 'User')], max_length=50),
        ),
    ]
