# Generated by Django 4.2 on 2024-10-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_user_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('medico_veterinario', 'Medico Vet'), ('groomer', 'Groomer'), ('atendente_saude', 'Atendente Saude'), ('atendente_hotel', 'Atendente Hotel'), ('atendente_loja', 'Atendente Loja'), ('atendente_banhotosa', 'Atendente Banhotosa'), ('assistente_veterinario', 'Assist Vet'), ('estagiario', 'Estagiario'), ('caixa', 'Caixa'), ('zelador', 'Zelador'), ('entregador', 'Entregador'), ('superuser', 'Superuser'), ('user', 'User'), ('outro', 'Outro')], max_length=50),
        ),
    ]
