# Generated by Django 4.2 on 2024-10-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('saude', 'Saude'), ('hotel', 'Hotel'), ('banho/tosa', 'Banhotosa'), ('loja', 'Loja'), ('user', 'User'), ('geral', 'Geral'), ('superuser', 'Superuser')], max_length=50),
        ),
    ]
