# Generated by Django 4.2 on 2024-11-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_user_keycloak_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='keycloak_id',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_service_id',
            field=models.UUIDField(default='fb156a2d-a4e6-42ce-a164-0bf21afd962b', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
