# Generated by Django 4.2 on 2024-11-01 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_user_keycloak_id_user_auth_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='esse', editable=False, max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^(?!.*[_-]{2})(?![-_])(?=.{1,25}$)[A-Za-z0-9._-]+(?<![-_])$', message='Username inválido. Deve ter no máximo 25 caracteres, pode conter letras, números, ponto, sublinhado ou hífen, não pode começar ou terminar com um caractere especial, e não pode ter caracteres especiais consecutivos.')]),
            preserve_default=False,
        ),
    ]
