# Generated by Django 4.2 on 2024-11-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_user_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdocument',
            unique_together={('doc_type', 'doc_number')},
        ),
    ]
