# Generated by Django 4.2 on 2025-08-06 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreatmentCycle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('complaits', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('dignosis', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('cancelado', 'Cancelado'), ('concluido', 'Concluido'), ('andamento', 'Andamento'), ('agendado', 'Agendado')], max_length=50)),
                ('pet_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_cycles', to='pet.pet')),
            ],
            options={
                'unique_together': {('pet_id', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('service_type', models.CharField(choices=[('consulta', 'Consulta'), ('exame', 'Exame'), ('cirurgia', 'Cirugia'), ('aplicacao de vacina', 'Vacina')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('prescription', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(editable=False)),
                ('return_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('assistant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_services', to='usuarios.user')),
                ('cycle_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='related_services', to='saude.treatmentcycle')),
                ('responsible_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_services', to='usuarios.user')),
            ],
            options={
                'unique_together': {('responsible_id', 'cycle_id')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('result_path', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_type_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='saude.examtype')),
                ('service_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='related_exams', to='saude.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
