# Generated by Django 4.2 on 2025-07-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_userdocument_unique_together'),
        ('pet', '0003_rename_species_id_breed_specie_id'),
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='assistant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_services', to='usuarios.user'),
        ),
        migrations.AlterUniqueTogether(
            name='treatmentcycle',
            unique_together={('pet_id', 'start_date')},
        ),
    ]
