# Generated by Django 4.2 on 2025-07-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_userdocument_unique_together'),
        ('saude', '0002_alter_service_assistant_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('responsible_id', 'ciclo_id')},
        ),
    ]
