# Generated by Django 4.2 on 2025-08-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_userdocument_unique_together'),
        ('saude', '0003_alter_service_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='ciclo_id',
            new_name='cycle_id',
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('responsible_id', 'cycle_id')},
        ),
    ]
