# Generated by Django 4.2 on 2025-04-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationservice',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_services', to='hotel.reservation'),
        ),
        migrations.AlterField(
            model_name='reservationservice',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hotel.service'),
        ),
    ]
