# Generated by Django 4.2 on 2025-04-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
