# Generated by Django 4.2 on 2025-08-06 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('pet', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('appointment_time', models.TimeField(choices=[('06:00', 'Hour 06 00'), ('06:30', 'Hour 06 30'), ('07:00', 'Hour 07 00'), ('07:30', 'Hour 07 30'), ('08:00', 'Hour 08 00'), ('08:30', 'Hour 08 30'), ('09:00', 'Hour 09 00'), ('09:30', 'Hour 09 30'), ('10:00', 'Hour 10 00'), ('10:30', 'Hour 10 30'), ('11:00', 'Hour 11 00'), ('11:30', 'Hour 11 30'), ('12:00', 'Hour 12 00'), ('12:30', 'Hour 12 30'), ('13:00', 'Hour 13 00'), ('13:30', 'Hour 13 30'), ('14:00', 'Hour 14 00'), ('14:30', 'Hour 14 30'), ('15:00', 'Hour 15 00'), ('15:30', 'Hour 15 30'), ('16:00', 'Hour 16 00'), ('16:30', 'Hour 16 30'), ('17:00', 'Hour 17 00'), ('17:30', 'Hour 17 30'), ('18:00', 'Hour 18 00'), ('18:30', 'Hour 18 30'), ('19:00', 'Hour 19 00'), ('19:30', 'Hour 19 30'), ('20:00', 'Hour 20 00'), ('20:30', 'Hour 20 30'), ('21:00', 'Hour 21 00'), ('21:30', 'Hour 21 30')])),
                ('date', models.DateField()),
                ('func_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='usuarios.user')),
                ('pet_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('execution_time', models.TimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductUsed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_services', to='produtos.product')),
                ('service_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_used', to='banhotosa.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('charged_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='banhotosa.appointment')),
                ('service_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='banhotosa.servicetype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productused',
            constraint=models.UniqueConstraint(fields=('product_id', 'service_type_id'), name='unique_product_id_service_type_id'),
        ),
        migrations.AddConstraint(
            model_name='appointmentservice',
            constraint=models.UniqueConstraint(fields=('appointment_id', 'service_type_id'), name='unique_appointment_service'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('date', 'appointment_time', 'func_id'), name='unique_date_func_appointment_time'),
        ),
    ]
