# Generated by Django 4.2 on 2024-10-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banhotosa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='product_used_id',
        ),
    ]
