# Generated by Django 4.2 on 2025-04-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_rename_species_id_breed_specie_id'),
        ('produtos', '0001_initial'),
        ('banhotosa', '0002_remove_servicetype_product_used_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetype',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='appointment_id',
        ),
        migrations.AddField(
            model_name='productused',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pet.pet'),
        ),
        migrations.AlterField(
            model_name='productused',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_services', to='produtos.product'),
        ),
        migrations.AlterField(
            model_name='productused',
            name='service_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_used', to='banhotosa.servicetype'),
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charged_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='banhotosa.appointment')),
                ('service_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='banhotosa.servicetype')),
            ],
        ),
    ]
