# Generated by Django 4.2 on 2025-05-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_rename_species_id_breed_specie_id'),
        ('banhotosa', '0003_rename_price_servicetype_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(choices=[('06:00', 'Hour 06 00'), ('06:30', 'Hour 06 30'), ('07:00', 'Hour 07 00'), ('07:30', 'Hour 07 30'), ('08:00', 'Hour 08 00'), ('08:30', 'Hour 08 30'), ('09:00', 'Hour 09 00'), ('09:30', 'Hour 09 30'), ('10:00', 'Hour 10 00'), ('10:30', 'Hour 10 30'), ('11:00', 'Hour 11 00'), ('11:30', 'Hour 11 30'), ('12:00', 'Hour 12 00'), ('12:30', 'Hour 12 30'), ('13:00', 'Hour 13 00'), ('13:30', 'Hour 13 30'), ('14:00', 'Hour 14 00'), ('14:30', 'Hour 14 30'), ('15:00', 'Hour 15 00'), ('15:30', 'Hour 15 30'), ('16:00', 'Hour 16 00'), ('16:30', 'Hour 16 30'), ('17:00', 'Hour 17 00'), ('17:30', 'Hour 17 30'), ('18:00', 'Hour 18 00'), ('18:30', 'Hour 18 30'), ('19:00', 'Hour 19 00'), ('19:30', 'Hour 19 30'), ('20:00', 'Hour 20 00'), ('20:30', 'Hour 20 30'), ('21:00', 'Hour 21 00'), ('21:30', 'Hour 21 30')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pet_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pet.pet'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('date', 'appointment_time', 'func_id'), name='unique_date_func_appointment_time'),
        ),
    ]
