# Generated by Django 4.2 on 2025-07-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhotosa', '0004_alter_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointmentservice',
            constraint=models.UniqueConstraint(fields=('appointment_id', 'service_type_id'), name='unique_appointment_service'),
        ),
        migrations.AddConstraint(
            model_name='productused',
            constraint=models.UniqueConstraint(fields=('product_id', 'service_type_id'), name='unique_product_id_service_type_id'),
        ),
    ]
